### ISSUE TITLE
neovim support?

### ISSUE THREAD

**Issue by leemhenson** [heavenshell/vim-flood#4]
Hi. Interesting plugin! Do you have any plans to support Neovim, or is it likely to stay Vim 8+ only?

**Comment by heavenshell** [comment]
@leemhenson 
Thank you for taking an interest in vim-flood.
I don't have any plan to support neovim(I don't use neovim).
sorry.

> is it likely to stay Vim 8+ only?

yep, `+channel` and `+job` required.
